const sampleVideos = [
  {
    userId: "507f1f77bcf86cd799439011",
    url: "https://example.com/videos/v1.mp4",
    filename: "v1.mp4",
    direction: "FRONT",
    title: "Morning Yoga Routine for Beginners",
    description:
      "A 15-minute yoga session to kickstart your day with flexibility and calm.",
    hashtags: ["yoga", "morningroutine", "fitness", "beginners"],
    visibility: "PUBLIC",
    views: 120,
  },
  {
    userId: "507f1f77bcf86cd799439012",
    url: "https://example.com/videos/v2.mp4",
    filename: "v2.mp4",
    direction: "BACK",
    title: "Vegan Dinner Recipes Under 30 Minutes",
    description: "Quick and delicious plant-based meals for busy weeknights.",
    hashtags: ["vegan", "cooking", "recipes", "quickmeals"],
    visibility: "PUBLIC",
    views: 85,
  },
  {
    userId: "507f1f77bcf86cd799439013",
    url: "https://example.com/videos/v3.mp4",
    filename: "v3.mp4",
    direction: "FRONT",
    title: "Top 5 Gaming Headsets of 2025",
    description: "Reviewing the best headsets for immersive gaming this year.",
    hashtags: ["gaming", "tech", "headsets", "reviews"],
    visibility: "PUBLIC",
    views: 300,
  },
  {
    userId: "507f1f77bcf86cd799439014",
    url: "https://example.com/videos/v4.mp4",
    filename: "v4.mp4",
    direction: "BACK",
    title: "DIY Home Decor on a Budget",
    description: "Transform your space with these affordable DIY projects.",
    hashtags: ["diy", "homedecor", "budgetfriendly", "crafts"],
    visibility: "FOLLOWERS_ONLY",
    views: 45,
  },
  {
    userId: "507f1f77bcf86cd799439015",
    url: "https://example.com/videos/v5.mp4",
    filename: "v5.mp4",
    direction: "FRONT",
    title: "Street Photography Tips for Beginners",
    description: "Learn how to capture stunning urban shots with your camera.",
    hashtags: ["photography", "streetphotography", "beginners", "tips"],
    visibility: "PUBLIC",
    views: 200,
  },
  {
    userId: "507f1f77bcf86cd799439016",
    url: "https://example.com/videos/v6.mp4",
    filename: "v6.mp4",
    direction: "BACK",
    title: "How to Train Your Puppy Basics",
    description: "Essential training tips for new puppy owners.",
    hashtags: ["pets", "puppytraining", "dogcare", "tips"],
    visibility: "PUBLIC",
    views: 150,
  },
  {
    userId: "507f1f77bcf86cd799439017",
    url: "https://example.com/videos/v7.mp4",
    filename: "v7.mp4",
    direction: "FRONT",
    title: "Minimalist Skincare Routine",
    description: "Simplify your skincare with these 5 must-have products.",
    hashtags: ["skincare", "minimalism", "beauty", "routine"],
    visibility: "PUBLIC",
    views: 90,
  },
  {
    userId: "507f1f77bcf86cd799439018",
    url: "https://example.com/videos/v8.mp4",
    filename: "v8.mp4",
    direction: "BACK",
    title: "Epic Mountain Biking Trails",
    description: "Exploring the best trails for adrenaline junkies.",
    hashtags: ["mountainbiking", "adventure", "outdoors", "trails"],
    visibility: "PUBLIC",
    views: 250,
  },
  {
    userId: "507f1f77bcf86cd799439019",
    url: "https://example.com/videos/v9.mp4",
    filename: "v9.mp4",
    direction: "FRONT",
    title: "Coding a Website from Scratch",
    description:
      "Step-by-step guide to building a responsive site with HTML and CSS.",
    hashtags: ["coding", "webdevelopment", "tutorial", "tech"],
    visibility: "PUBLIC",
    views: 400,
  },
  {
    userId: "507f1f77bcf86cd799439020",
    url: "https://example.com/videos/v10.mp4",
    filename: "v10.mp4",
    direction: "BACK",
    title: "Best Coffee Shops in NYC",
    description: "A tour of hidden gems for coffee lovers in New York.",
    hashtags: ["coffee", "nyc", "travel", "foodie"],
    visibility: "PUBLIC",
    views: 130,
  },
  {
    userId: "507f1f77bcf86cd799439021",
    url: "https://example.com/videos/v11.mp4",
    filename: "v11.mp4",
    direction: "FRONT",
    title: "Advanced Yoga Poses Tutorial",
    description: "Master challenging poses with this expert guide.",
    hashtags: ["yoga", "fitness", "advanced", "tutorial"],
    visibility: "PUBLIC",
    views: 175,
  },
  {
    userId: "507f1f77bcf86cd799439022",
    url: "https://example.com/videos/v12.mp4",
    filename: "v12.mp4",
    direction: "BACK",
    title: "Healthy Smoothie Recipes",
    description: "Blend up these nutrient-packed drinks in minutes.",
    hashtags: ["smoothies", "healthy", "recipes", "food"],
    visibility: "PUBLIC",
    views: 60,
  },
  {
    userId: "507f1f77bcf86cd799439023",
    url: "https://example.com/videos/v13.mp4",
    filename: "v13.mp4",
    direction: "FRONT",
    title: "Unboxing the Latest Smartphone",
    description: "First look at the newest tech gadget of 2025.",
    hashtags: ["tech", "unboxing", "smartphone", "reviews"],
    visibility: "PUBLIC",
    views: 500,
  },
  {
    userId: "507f1f77bcf86cd799439024",
    url: "https://example.com/videos/v14.mp4",
    filename: "v14.mp4",
    direction: "BACK",
    title: "Gardening Tips for Small Spaces",
    description: "Grow your own food even in tiny apartments.",
    hashtags: ["gardening", "smallspaces", "urbanliving", "tips"],
    visibility: "FOLLOWERS_ONLY",
    views: 30,
  },
  {
    userId: "507f1f77bcf86cd799439025",
    url: "https://example.com/videos/v15.mp4",
    filename: "v15.mp4",
    direction: "FRONT",
    title: "Beginner Guitar Lessons",
    description: "Learn your first chords with this easy tutorial.",
    hashtags: ["guitar", "music", "beginners", "lessons"],
    visibility: "PUBLIC",
    views: 220,
  },
  {
    userId: "507f1f77bcf86cd799439026",
    url: "https://example.com/videos/v16.mp4",
    filename: "v16.mp4",
    direction: "BACK",
    title: "Backpacking Europe on a Budget",
    description: "Tips and tricks for affordable travel across Europe.",
    hashtags: ["travel", "backpacking", "budget", "europe"],
    visibility: "PUBLIC",
    views: 180,
  },
  {
    userId: "507f1f77bcf86cd799439027",
    url: "https://example.com/videos/v17.mp4",
    filename: "v17.mp4",
    direction: "FRONT",
    title: "Keto Dessert Recipes",
    description: "Satisfy your sweet tooth without breaking your diet.",
    hashtags: ["keto", "desserts", "recipes", "lowcarb"],
    visibility: "PUBLIC",
    views: 95,
  },
  {
    userId: "507f1f77bcf86cd799439028",
    url: "https://example.com/videos/v18.mp4",
    filename: "v18.mp4",
    direction: "BACK",
    title: "Sunset Hike Vlog",
    description: "Join me on a scenic hike with breathtaking views.",
    hashtags: ["hiking", "outdoors", "vlog", "nature"],
    visibility: "PUBLIC",
    views: 140,
  },
  {
    userId: "507f1f77bcf86cd799439029",
    url: "https://example.com/videos/v19.mp4",
    filename: "v19.mp4",
    direction: "FRONT",
    title: "AI Tools for Productivity",
    description: "Boost your workflow with these cutting-edge AI apps.",
    hashtags: ["ai", "productivity", "tech", "tools"],
    visibility: "PUBLIC",
    views: 350,
  },
  {
    userId: "507f1f77bcf86cd799439030",
    url: "https://example.com/videos/v20.mp4",
    filename: "v20.mp4",
    direction: "BACK",
    title: "Cat Care 101",
    description:
      "Everything you need to know to keep your feline friend happy.",
    hashtags: ["cats", "petcare", "tips", "animals"],
    visibility: "PUBLIC",
    views: 110,
  },
];

const mongoose = require("mongoose");
const Video = require("./models/video.model");
require("dotenv").config();

const uri = process.env.MONGODB_CLUSTER_URI;
mongoose
  .connect(uri, { dbName: "tastetube" })
  .then(async () => {
    await Video.insertMany(sampleVideos);
    console.log("Sample videos inserted successfully!");
    mongoose.connection.close();
  })
  .catch((err) => console.error("Error inserting videos:", err));
